### ISSUE TITLE
Wrong value logged : Media Session summary, media_content_time_spent

### ISSUE THREAD

**Issue by CharlesMcD** [mParticle/mparticle-android-media-sdk#13]
The data in the `media_content_time_spent` attribute seems to always be wrong on Android. This value is supposed to represent the time spent watching content on during the session, but the value returned is always way too big.

**media_content_time_spent : 1.673905917E9**

I'm pretty sure there's an error in the `mediaContentTimeSpent` calculation.

https://github.com/mParticle/mparticle-android-media-sdk/blob/6d4e218a1c2cc85bee48f5d12c037995a3e16494/media/src/main/java/com/mparticle/media/MediaSession.kt#L82-L87

storedPlaybackTime = 0
currentPlayheadPosition : 73047
System.currentTimeMillis() : 1673905852820

0 + (1673905852820 - 73047) / 1000 = 1673905779.773 which is not the expected value, it should be something like '218.0' like the `media_time_spent` in the provided screenshot.

Here's what I see using the "live stream" page in the mParticle dashboard.
<img width="405" alt="Capture d’écran, le 2023-01-16 à 16 53 35" src="https://user-images.githubusercontent.com/6673075/212771640-b10b220b-67e3-4c66-a993-b2dfde0fc9c9.png">

In my code I call the `logMediaSessionEnd` function like this : 
<img width="865" alt="Capture d’écran, le 2023-01-16 à 16 50 21" src="https://user-images.githubusercontent.com/6673075/212771666-47cc43d0-4bcd-498d-a97d-8ffaf07985c4.png">

**Comment by CharlesMcD** [comment]
If it can be helpful, the value is correct on iOS. Here's what is done on iOS Media SDK :

```
private var mediaContentTimeSpent: Double {
    get { //total seconds spent playing content
        if (self.currentPlaybackStartTimestamp != nil) {
            return self.storedPlaybackTime + Date().timeIntervalSince(self.currentPlaybackStartTimestamp!)
        } else {
            return self.storedPlaybackTime
        }
    }
}
```

**Comment by mmustafa-tse** [comment]
Hi @CharlesMcD,

A PR went to fix this issue, will update you back once its released.

Thanks,

**Comment by CharlesMcD** [comment]
Thanks for the follow-up
